name: dump1090
version: 0
summary: ADS-B dumper and viewer
description: View flights in your area with a cheap RTL-SDR dongle
confinement: devmode
grade: devel

apps:
  dump1090:
    command: dump1090-service
    daemon: simple
    plugs:
      - network
      - network-bind
  view1090:
    command: view1090-service
    daemon: simple
    plugs:
      - network
      - network-bind


parts:
  dump1090:
    plugin: make
    build-packages: [pkg-config, librtlsdr-dev]
    stage-packages: [librtlsdr0]
    source: .
  wrappers:
    plugin: dump
    source: .
    filesets:
      services: [dump1090-service, view1090-service]
    stage: [$services]
    snap: [$services]

